apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-threaded
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-threaded
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: cantino/huginn-single-process
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        args:
        - /scripts/init
        - bin/threaded.rb
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: {{ template "fullname" . }}-mysql
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: APP_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: app-secret-token
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: database-password 
        - name: DATABASE_USERNAME
          value: {{ default "huginn" .Values.databaseUser| quote }}
        - name: DATABASE_ADAPTER
          value: "mysql2"
        - name: DATABASE_NAME
          value: "huginn"
        readinessProbe:
          exec:
            command:
            - /app/bin/bundle 
            - exec 
            - rake
            - db:version
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
